/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_cross_util_DiffUtil */

#ifndef _Included_com_cross_util_DiffUtil
#define _Included_com_cross_util_DiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cross_util_DiffUtil
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cross_util_DiffUtil_genDiff
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
